[package]
name = "markdown-preprocessor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mdp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
regex = "1.12.2"
